# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12955b898047a449c234696e02f34aea"
name = "Store Locator by Win-Win Apps"
application_url = "https://example.com"
embedded = true
handle = "ww-store-locator-dev"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
